Use descriptive names for constants
SAP/styleguides pull request #198
Opened 2021-04-17 08:58 UTC by pokrakam

There is still a lot of code being written in the style of `CONSTANTS c_01 ... VALUE '01'.`,  I suggest this should be emphasised in it's own section. 
We could put this in the "Use descriptive names'' section too, but I feel it is better among constants because it's more obvious that we should look to enumeration classes first.

2021-04-23 12:08 UTC, schmelto approved these changes

2022-03-18 08:24 UTC, HrFlorianHoffmann commented
Yes, I agree. This point could need some repetition. Two suggestions:
- Let's make this the second sub-section inside the _Constants_ section, directly after _Use constants instead of magic numbers_ It fits better at the front there because it has more a general or introductive character and should come before we dive into the technical details of how to implement in the other two sub-sections. It also fits in nicely beside the general observation to not use magic numbers. 
- Let's add a link to the section _Use descriptive names_. Maybe a quoted paragrapth at the end:
> This is a repetition of the rule [Use descriptive names](#use-descriptive-names), specifically for constants.
@pokrakam Can you do these changes in your original branch? It's not inside this repository, so I cannot directly edit it. Or should I move the suggested changes over and add them from an own branch?

2022-03-18 08:24 UTC, HrFlorianHoffmann requested changes
⬆

2022-03-22 22:48 UTC, pokrakam commented
@HrFlorianHoffmann sure I can update this, bit busy  but will get to it in the next couple of days.

2023-03-14 13:26 UTC, ConjuringCoffee commented on clean-abap/CleanABAP.md
> +CONSTANTS c_status_inactive TYPE mmsta VALUE '90'.
The "good" example should not contain any prefix, see rule "Avoid encodings, esp. Hungarian notation and prefixes"

2023-08-09 20:37 UTC, closed without merging