Add Sonar Cloud to list of Code Analysis Tools
SAP/styleguides pull request #200
Opened 2021-04-21 14:22 UTC by matt1as

2021-04-21 14:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/styleguides?pullRequest=200) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/styleguides?pullRequest=200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/styleguides?pullRequest=200) it.</sub>

2021-04-22 10:03 UTC, xtough requested changes
@larshp FYI, for some reason I cannot add you as reviewer.

@matt1as are you affiliated to Sonarsource? It sounds a bit like marketing, which makes me feel a bit uneasy. See also my inline comments on typos.

2021-04-22 12:04 UTC, matt1as commented on abap-code-review/src/tools.adoc
> +link:https://sonarcloud.io/[SonarCloud] is a product for Continuous Code Quality online, totally free for open-source projects. It supports multiple languages, Abap serialized by AbapGIT being one of
I'm not affiliated with SonarSource, we are a paying customers that use SonarCloud for our C#, JS and ABAP code review (together with ATC). We find that the two tools complement each other and catches different kinds of errors/mistakes. I did not know it existed until 2 years ago, and I think there are more ABAP-shops that would benefit from using it.

Please suggest how I could make it less "marketing".

2021-04-22 15:03 UTC, xtough commented
Thanks for explaining, @matt1as . And first of all, thanks for your contribution! 👍 

I had a brief conversation with @larshp on this PR. We felt that we should make clear in the tools chapter which kind of tools we are discussing. There are basically 3 types:
1. provided by SAP -- usually part of your support contract with SAP
2. Open source -- Mostly projects from the ecosystem around dotabap.org , best effort support, take it or leave it
3. Third party -- subject to individual licenses (like GitHub, GitLab, and SonarSource for that matter)

The tools chapter is currently structured along tool purposes as a different dimension. Nevertheless, I would prefer to move this section to a "4.5.3 Third party tools" instead of the currently too prominent "4.7 SonarCloud". 

In other words: Move it up between ``==== abapLint`` and ``=== abap-openapi-client`` and increase its title indentation by one ``=``

2021-04-22 15:28 UTC, larshp commented on abap-code-review/src/tools.adoc
> +link:https://sonarcloud.io/[SonarCloud] is a product for Continuous Code Quality online, totally free for open-source projects. It supports multiple languages, Abap serialized by AbapGIT being one of
as a customer, and vendors basing products on top of opensource, consider choosing vendors which actively support open source

of cause open source is open, but its also open for customers to choose vendors

some people have spent a lot of time sharing, just like this document is shared openly

in my opinion, it's not helping to add a list of commercial only 3rd party vendors

2021-04-22 16:22 UTC, matt1as commented on abap-code-review/src/tools.adoc
> +link:https://sonarcloud.io/[SonarCloud] is a product for Continuous Code Quality online, totally free for open-source projects. It supports multiple languages, Abap serialized by AbapGIT being one of
SonarSource is actually a pretty good open source citizen; most of their products are open source under LGPL, but unfortunately the ABAP check is not one of them. 

They live on github, [https://github.com/SonarSource]

2021-04-23 07:30 UTC, xtough requested changes
I would suggest to make this even less prominent. So far we don't use Sonarsource in our example or anywhere else in the dotabap.org ecosystem and Sonarsource hasn't contributed anything yet either. It is OK to mention it for academic completeness but there is no need to advertise third party commercial offerings. The section title even leaves room for others...

2021-04-23 07:30 UTC, xtough commented on abap-code-review/src/tools.adoc
> +
```suggestion
==== Third party checks

There are other tools from third party vendors that can be also used for ABAP code analysis. 

For instance, link:https://www.sonarsource.com/abap/[SonarSource ABAP] can be used to check ABAP source serialized by abapGit. 
Their link:https://github.com/apps/sonarcloud[App] can be used to integrate it with GitHub-based CI pipelines.
```

2021-04-23 07:58 UTC, xtough requested changes
line feed missing, 
sorry, my fault

2021-04-23 07:58 UTC, xtough commented on abap-code-review/src/tools.adoc
>  === abap-openapi-client
```suggestion

=== abap-openapi-client
```
missing line feed to keep formatting intact

2021-04-23 08:05 UTC, xtough approved these changes
LGTM.
@larshp any objections?

2021-04-23 08:06 UTC, larshp commented
looks good, good to merge 👍

2021-04-23 08:34 UTC, merged