Clarify test features in product code
SAP/styleguides pull request #254
Opened 2021-10-16 15:08 UTC by pokrakam

Closes #247

2022-11-28 15:52 UTC, N2oB6n-SAP commented on clean-abap/CleanABAP.md
> +    - [Don't add unit test features to productive code](#dont-add-unit-test-features-to-productive-code)
I agree about the misleading title. The arguments in #247 nicely highlight that productive code needs to be changed to be made testable. The notable distinction is structural rework (i.e. refactoring) and adding features just for the sake of testing (let's say "test-driven pollution").

2022-11-28 15:52 UTC, N2oB6n-SAP commented on clean-abap/CleanABAP.md
> +    - [Don't add unit test features to productive code](#dont-add-unit-test-features-to-productive-code)
Full ack.

2022-11-28 16:06 UTC, N2oB6n-SAP commented on clean-abap/CleanABAP.md
> +For reasons already described under [Test Seams](#use-test-seams-as-temporary-workaround), adding test features to product code should also be avoided.
I believe we should leave even less room for ambiguity than "test features" / "test code". For example "...adding parts to the production code that are solely used for testing should also be avoided."

2022-11-28 16:15 UTC, N2oB6n-SAP commented on clean-abap/CleanABAP.md
> +    - [Don't add unit test features to productive code](#dont-add-unit-test-features-to-productive-code)
I am afraid the real culprit is the german false friend compound word "Produktivcode" which managed to seep into the guide as well. For the sake of consistency we might use productive but generally speaking we really ought to switch it to something else...

2023-01-17 13:51 UTC, N2oB6n-SAP requested changes

2023-01-23 12:43 UTC, HrFlorianHoffmann commented on clean-abap/CleanABAP.md
> +    - [Don't add unit test features to productive code](#dont-add-unit-test-features-to-productive-code)
Let's address this in a separate PR and change it from "productive" to "production" consistently.

2023-01-23 12:47 UTC, HrFlorianHoffmann commented on clean-abap/CleanABAP.md
> +Note that test features for intended for the end user, e.g. simulated posting or running a report in test mode, form part of the application domain and remain a valid use case.
⬆️ I like this suggestion. It's a bit clearer than the `->is_test_mode alone`, which could just as well be part of a regular piece of production code.

2023-03-06 15:19 UTC, N2oB6n-SAP commented on clean-abap/CleanABAP.md
> +#### Don't add unit test features to productive code
obsolete with latest changes -> marking as resolved

2023-03-06 15:33 UTC, N2oB6n-SAP requested changes
I support all proposed changes (using "production" everywhere and clarifying that "test" refers to automated tests).

Only thing that is left is the tiny grammar mistake that I believe to have spotted.

2023-03-09 09:47 UTC, merged