Removal of dead or questionable links in section "split-method-instead-of-boolean-input-parameter" across multiple languages
SAP/styleguides pull request #345
Opened 2023-11-28 10:19 UTC by SABECK1

Related to this [issue](https://github.com/SAP/styleguides/issues/344). Removal of certain links in the English, German and French version of the document.

2023-12-11 15:09 UTC, sautermi0 approved these changes

2023-12-11 15:47 UTC, N2oB6n-SAP requested changes
I'd rather replace the sources with archive.org URLs so we get to keep the reasoning. (I will provide a commit.)

2023-12-11 15:53 UTC, N2oB6n-SAP reviewed
I have replaced all bad links with archived versions but this got me wondering: Do we want to mandate using archived versions of external links in general?

2023-12-11 15:54 UTC, N2oB6n-SAP approved these changes

2023-12-12 07:32 UTC, sautermi0 approved these changes

2023-12-12 07:50 UTC, merged